# Generated by Django 3.2 on 2023-06-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblAlumno',
            fields=[
                ('alumno_id', models.AutoField(primary_key=True, serialize=False)),
                ('alumno_nombre', models.CharField(max_length=255)),
                ('alumno_apellido', models.CharField(max_length=255)),
                ('alumno_fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('alumno_foto', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_alumno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAlumnoHorario',
            fields=[
                ('alumno_horario_id', models.AutoField(primary_key=True, serialize=False)),
                ('alumno_horario_dia', models.CharField(max_length=45)),
                ('alumno_horario_ingreso', models.TimeField()),
                ('alumno_horario_salida', models.TimeField()),
            ],
            options={
                'db_table': 'tbl_alumno_horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblApoderado',
            fields=[
                ('apoderado_id', models.AutoField(primary_key=True, serialize=False)),
                ('apoderado_nombre', models.CharField(max_length=255)),
                ('apoderado_apellido', models.CharField(max_length=255)),
                ('apoderado_telefono', models.CharField(max_length=255)),
                ('apoderado_documento_identidad', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tbl_apoderado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblCargo',
            fields=[
                ('cargo_id', models.AutoField(primary_key=True, serialize=False)),
                ('cargo_nombre', models.CharField(max_length=45)),
                ('cargo_sueldo', models.FloatField()),
            ],
            options={
                'db_table': 'tbl_cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblColegio',
            fields=[
                ('colegio_id', models.AutoField(primary_key=True, serialize=False)),
                ('colegio_nombre', models.CharField(max_length=255)),
                ('colegio_direccion', models.CharField(max_length=255)),
                ('colegio_telefono', models.CharField(max_length=20)),
                ('colegio_contacto', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_colegio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblEmpleado',
            fields=[
                ('empleado_id', models.AutoField(primary_key=True, serialize=False)),
                ('empleado_nombre', models.CharField(max_length=255)),
                ('empleado_apellido', models.CharField(max_length=255)),
                ('empleado_telefono', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tbl_empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblEmpleadoHonorario',
            fields=[
                ('empleado_honorario_id', models.AutoField(primary_key=True, serialize=False)),
                ('empleado_honorario_monto', models.FloatField()),
                ('empleado_honorario_fecha', models.DateField()),
            ],
            options={
                'db_table': 'tbl_empleado_honorario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblFormaPago',
            fields=[
                ('forma_pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('forma_pago_nombre', models.CharField(max_length=45)),
                ('forma_pago_referencia', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_forma_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblGrado',
            fields=[
                ('grado_id', models.AutoField(primary_key=True, serialize=False)),
                ('grado_nombre', models.CharField(max_length=50)),
                ('grado_nivel', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tbl_grado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblMovilidad',
            fields=[
                ('movilidad_id', models.AutoField(primary_key=True, serialize=False)),
                ('movilidad_tipo_servicio', models.CharField(max_length=45)),
                ('movilidad_turno', models.CharField(max_length=45)),
                ('movilidad_seccion', models.CharField(max_length=45)),
                ('movilidad_docente', models.CharField(max_length=255)),
                ('movilidad_pago', models.FloatField()),
            ],
            options={
                'db_table': 'tbl_movilidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblMovilidadPago',
            fields=[
                ('movilidad_pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('movilidad_pago_fecha', models.DateField()),
                ('movilidad_pago_monto', models.FloatField()),
            ],
            options={
                'db_table': 'tbl_movilidad_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblMovilidadRuta',
            fields=[
                ('movilidad_ruta_id', models.AutoField(primary_key=True, serialize=False)),
                ('movilidad_ruta_direccion', models.CharField(max_length=255)),
                ('movilidad_ruta_hora_recojo', models.TimeField(blank=True, null=True)),
                ('movilidad_ruta_hora_retorno', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_movilidad_ruta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblParentesco',
            fields=[
                ('parentesco_id', models.AutoField(primary_key=True, serialize=False)),
                ('parentesco_nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tbl_parentesco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblTipoMantenimiento',
            fields=[
                ('tipo_mantenimiento_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_mantenimiento_nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tbl_tipo_mantenimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVehiculo',
            fields=[
                ('vehiculo_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehiculo_placa', models.CharField(max_length=20)),
                ('vehiculo_km', models.FloatField()),
                ('vehiculo_marca', models.CharField(max_length=45)),
                ('vehiculo_modelo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tbl_vehiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVehiculoDocumento',
            fields=[
                ('vehiculo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('vehiculo_documento_nombre', models.CharField(max_length=45)),
                ('vehiculo_documento_fecha_vencimiento', models.DateField()),
            ],
            options={
                'db_table': 'tbl_vehiculo_documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVehiculoGasto',
            fields=[
                ('vehiculo_gasto_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehiculo_gasto_descripcion', models.TextField(blank=True, null=True)),
                ('vehiculo_gasto_monto', models.FloatField(blank=True, null=True)),
                ('vehiculo_gasto_fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_vehiculo_gasto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVehiculoMantenimiento',
            fields=[
                ('vehiculo_mantenimiento_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehiculo_mantenimiento_fecha', models.DateField()),
                ('vehiculo_mantenimiento_observacion', models.TextField(blank=True, null=True)),
                ('vehiculo_mantenimiento_fecha_futura', models.DateField()),
                ('vehiculo_mantenimiento_km', models.FloatField()),
            ],
            options={
                'db_table': 'tbl_vehiculo_mantenimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblZona',
            fields=[
                ('zona_id', models.AutoField(primary_key=True, serialize=False)),
                ('zona_nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_zona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('tipo_gasto_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_gasto_nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tipo_gasto',
                'managed': False,
            },
        ),
    ]
